### ISSUE TITLE
Video not shown in Starling-project, sound-only

### ISSUE THREAD

**Issue by xs2bas** [myflashlab/surfaceVideoPlayer-ANE#10]
I'm trying to embed the trial-version of the Surface embedded video player in my project, but can't get it to work completely.
To test, first I build a plain version with the example-code supplied, which worked perfect.
The project I try to implement it to is build with Starling. The problem is that when I start the video I hear it play, but I don't see it.
To which stage do I have to add it when using 'new SurfacePlayer(???);' I tried the native-stage and the Starling-stage, but can't get it to work.

**Comment by crooksy88** [comment]
It's the Flash stage (your document class's stage).
e.g. In my Starling app the document class is StartUp.

public static var _stage:Stage;
_stage = this.stage;

_surfaceVideo = new SurfacePlayer(StartUp._stage);

**Comment by xs2bas** [comment]
That's what I did, but doesn't work :(

**Comment by crooksy88** [comment]
I wonder if whether you using the trial version is causing this. Does the trial version require a button tap before things will work?

**Comment by myflashlab** [comment]
As @crooksy88 suggested, when using the demo ANE, you need to make sure you are not calling any of the ANE method prior to touching the dialog box OK button.

**Comment by xs2bas** [comment]
On what call is the dialog box shown?

This is the simplified code I use:
`		

		private var _ex:SurfacePlayer;

		public function video():void {
			addEventListener (Event.ADDED, f_added);
		}

		private function f_added(e:Event):void {
			VideoPlayer.clubId = "paypal-address-you-used-to-join-the-club";
			
			// initialize the extension
			_ex = new SurfacePlayer(Globals.nativeRootClass);
			trace("added", _ex);
			//var _ex:SurfacePlayer = new SurfacePlayer(Globals.nativeStage);
			
			// copy test video to sdcard
			//var src:File = File.applicationDirectory.resolvePath("liedje.mp4");
			var src:File = File.applicationDirectory.resolvePath("testVideoPlayerSurface.mp4");
			var dis:File = File.applicationStorageDirectory.resolvePath(src.name);
			
			trace("a demo video is copied to applicationStorageDirectory so we can play it back!");
			if (!dis.exists) src.copyTo(dis);
			
			var w:int = 200;
			var h:int = 80;
			var x:int = w * 0.5;
			var y:int = 50;
				
			_ex.init(x, y, w, h, true); 
			
			_ex.attachVideo(dis, SurfaceVideoLocation.ON_APP);

			// just for testing purpose, wait 10 seconds and then start playing
			TweenMax.delayedCall (10, play);
		}
		
		private function play():void {
			trace("_ex", _ex);
			_ex.play();
		} 
			

`

**Comment by crooksy88** [comment]
Try it this way... A native dialog should appear as you launch your app. This is only there on the test version of the ANE. It might say something like 'trial version'.

 private var _ex:SurfacePlayer;

 public function video():void {
addEventListener (Event.ADDED, f_added);
}

private function f_added(e:Event):void {
TweenMax.delayedCall (10, createPlayer);
}

private function createPlayer():void {

VideoPlayer.clubId = "paypal-address-you-used-to-join-the-club";

        // initialize the extension
        _ex = new SurfacePlayer(Globals.nativeStage);
        trace("added", _ex);

        // copy test video to sdcard
        //var src:File = File.applicationDirectory.resolvePath("liedje.mp4");
        var src:File = File.applicationDirectory.resolvePath("testVideoPlayerSurface.mp4");
        var dis:File = File.applicationStorageDirectory.resolvePath(src.name);

        trace("a demo video is copied to applicationStorageDirectory so we can play it back!");
        if (!dis.exists) src.copyTo(dis);

        var w:int = 200;
        var h:int = 80;
        var x:int = w * 0.5;
        var y:int = 50;

        _ex.init(x, y, w, h, true); 

        _ex.attachVideo(dis, SurfaceVideoLocation.ON_APP);

}

**Comment by xs2bas** [comment]
Finally got it to work.
First I initialize the extension, than after some seconds the player-creation.
Thanks for helping!
