### ISSUE TITLE
Sound plays but not video

### ISSUE THREAD

**Issue by calibrae** [myflashlab/surfaceVideoPlayer-ANE#11]
Hi,

I've been trying everything with the demo version. 
I can play videos (even from the applicationDirectory, by the way) but the screen stays dark. 
Sounds play fine tho. 

Using AIR 21 and IOS SDK 9.2. Any help would be greatly appreciated since normal video playback on iOS with AIR is giving us headaches. 

Thanks guys.

**Comment by myflashlab** [comment]
We just tested the ANE with Air 22 and it works totally normal. (FYI: you can't publish .ipa to itunes using Air 21 anyway, so you should consider upgrading to Air22 even if it is in beta mode as right now)

Yet, please test your app with this video here https://github.com/myflashlab/surfaceVideoPlayer-ANE/tree/master/FD/bin maybe your video format has a problem displaying the video?

**Comment by calibrae** [comment]
Trying that right now. Thanks for the fast reply.

**Comment by calibrae** [comment]
Tried in a mini project to display your video. Did not work either. I can hear the sound playing but nothing gets displayed. 
I've pushed the project on github here if you have time to take a look https://github.com/calibrae/SurfaceVIdeoPlayerTest
Thanks again !

**Comment by myflashlab** [comment]
Could you also try this on a non-starling project to see if the video will be shown? I want to know if this has anything to do with the Starling gpu rendering...?

**Comment by myflashlab** [comment]
you may also check this out first: https://github.com/myflashlab/surfaceVideoPlayer-ANE/issues/10

**Comment by calibrae** [comment]
Hi, 
tried to remove starling and add a 10 seconds wait before trying to run the video. It does not change a thing, Video plays, I can hear the sound, but nothing on the screen. 
You can check out the latest master from my repository

And by the way, I don't have the trial version popup anymore. I downloaded the ane from the /FD/lib folder. 

Thanks again

**Comment by mesaglam** [comment]
Hi, i wan't to play remote stream (ex: from vimeo) with resizing and repositioning option, but not suported at the moment. Do you have any ane solution about that? 

Thanks for all...

**Comment by myflashlab** [comment]
@calibrae It seems like you were right! the video was not drawn to the stage on older iOS devices (and on random bases!). We accidentally came across this problem while working on a project. please update yourself to V3.2.0 and the problem will be solved. For future bug reports, please consider sending us a demo FlashDevelop project so we can easily run and duplicate the problem. That way, we will be able to fix the problem super fast. but when we are not able to see the bug, it's very hard to try to kill it! :D Thanks.

**Comment by myflashlab** [comment]
@mesaglam Supporting remote videos on a surface player like this is a huge work and we are not receiving much request for remote files at the moment. so It's not on our to-do list. unless you are willing to order it as a custom job, please [contact us here](http://www.myflashlabs.com/contact/).
