### ISSUE TITLE
SurfaceVideoANE to play the video from the internet?

### ISSUE THREAD

**Issue by mrgoonie** [myflashlab/surfaceVideoPlayer-ANE#12]
Ok, I know this ANE only use for playing local video. And I also know that Video Player ANE can play the video from the internet, but it play in FULLSCREEN mode. 

My question is, is there anyway I can play the video from the internet within the app - not in fullscreen mode?

Thanks,

**Comment by mesaglam** [comment]
Yes! I want to play remote video inside the app. Nearly one year passed. Still no luck? Weird...

**Comment by mrgoonie** [comment]
I believe the most difficult part is positioning & sizing the video, but I think it's still possible..

**Comment by myflashlab** [comment]
We have recently came up with a new solution on how to launch Native windows over AIR and we are working on a new release of all our ANEs which have native views over AIR, like this ANE, the RichWebview, etc. We're working on it guys, be patient. 👍

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
