### ISSUE TITLE
Detect click/touch events on surface player

### ISSUE THREAD

**Issue by MaximSpirin** [myflashlab/surfaceVideoPlayer-ANE#13]
Hello,
can you please let me know whether its possible to detect touches on surface player viewport? Does it dispatch something like MouseEvent.CLICK ?
Thanks,
Max

**Comment by myflashlab** [comment]
@MaximSpirin it doesn't. Yet, please let us know why that would be important to you? maybe we can consider adding this feature in future releases of the ANE.

**Comment by MaximSpirin** [comment]
Hello,
well it would be nice if you mention this on the product description page or at least in ASDoc.
We simply need to track touches on the particular videos. Its all about one OnClickListener.

**Comment by myflashlab** [comment]
Update yourself to V3.3.0 and you will have access to [touch events](https://github.com/myflashlab/surfaceVideoPlayer-ANE/blob/master/FD/src/Demo.as#L194-L197).
