### ISSUE TITLE
flv playback

### ISSUE THREAD

**Issue by MaximSpirin** [myflashlab/surfaceVideoPlayer-ANE#14]
Hello
does surface player support flv videos?

**Comment by myflashlab** [comment]
The short answer is now.
The Surface Player ANE uses native libraries to play videos. the below two links are good samples on what formats are supported by each platform:

on [Android](https://www.macxdvd.com/mac-dvd-video-converter-how-to/supported-video-format-for-android.htm)  
on [iOS](https://developer.apple.com/library/content/documentation/Miscellaneous/Conceptual/iPhoneOSTechOverview/MediaLayer/MediaLayer.html)
