### ISSUE TITLE
Video not showing on sample app

### ISSUE THREAD

**Issue by Tron307020** [myflashlab/surfaceVideoPlayer-ANE#15]
I've purchased the commercial version of this ANE. I am using Flash Builder 4.7 and am trying to do an initial compile of the demo for a standalone Android app (export with captive runtime). All the assets are included in the package, but when run on the phone (Galaxy S4), I do not see the video. The swf with the buttons for play, stop, etc... show up fine along with the "drag me" tab, but no video shows (and, of course, no audio either). Pressing play, pause, or seek seem to do nothing regarding the video. The swf container works as I can drag the "drag" tab and see the hilight states of the play/stop/etc... buttons. What could be causing this issue and what troubleshooting steps might I take to help track down the problem?

Edit: The supporting ANE's (overrideAir and androidSupport) are included in the build as well.

Thanks!

**Comment by myflashlab** [comment]
Are you receiving any error messages? Try connecting your device to your computer while watching the AndroidStudio logcat window. see if any error messages are logged there?

And is this happening on all your devices? or Galaxy S4 only?

**Comment by myflashlab** [comment]
Please update us on how you are doing in regard to this issue?

**Comment by Tron307020** [comment]
This was user error (my error) combined with the demo being prepared for iOS use with the Android functionality commented out. I got the demo working cross-platform by adding a conditional for the OS and using the documents directory for Android (along with playing from SurfaceVideoLocation.ON_SD_CARD). So:

if (Capabilities.version.substr(0,3) == "IOS") dis = File.applicationStorageDirectory.resolvePath(src.name); // this works for iOS
else dis = File.documentsDirectory.resolvePath(src.name); // this works for Android

and then, when the video is ready,

if (Capabilities.version.substr(0,3) == "IOS") _ex.attachVideo(dis, SurfaceVideoLocation.ON_APP); // iOS devices
else _ex.attachVideo(dis, SurfaceVideoLocation.ON_SD_CARD); // Android

Additionally, there was confusion about the Android permissions when the video player was ported to my actual app. I was building with AIR SDK 24 and had no problems when running the video on Android devices using less than OS 6.0. The documentation mentions you'd need to check the permissions manually when using AIR SDK 24+ (for storage, especially), but it worked fine on older Android devices with no manual check (but with the permissions requested in the xml manifest). However, on Android OS 6.0 and up, the manual check is required and the video would not work again (until storage permissions were granted). I've purchased the permissionCheck ANE for that and it works great.

**Comment by myflashlab** [comment]
Happy to see it's working fine. Moreover, you may also use the [os property](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/player/surface/SurfacePlayer.html#os) instead of checking for the operating system manually. ```if (Capabilities.version.substr(0,3)```
