### ISSUE TITLE
How to use URL instead of File?

### ISSUE THREAD

**Issue by leossmith** [myflashlab/surfaceVideoPlayer-ANE#16]
I want to use the player for a radio app which will use a stream (.m3u8) from the cloud. Does the player allow usage of such file? Is it possible to use a URL instead of a File?

Thank you.

**Comment by leossmith** [comment]
Bump. 

Is it possible? I want to create a streaming app, but couldn't manage to add the url as source

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
