### ISSUE TITLE
Surface Video in Starling app

### ISSUE THREAD

**Issue by crooksy88** [myflashlab/surfaceVideoPlayer-ANE#3]
Hi, 

Could you tell me whether a Surface Video presented within a Starling app can be displayed on the Starling display list, or must it sit on the Flash display list?

e.g. is it possible to have a Surface video within a moveable Starling DisplayObject?

Thanks,

Mark

**Comment by myflashlab** [comment]
yes it can but you should consider the following facts.

* any native content being added to the AdobeAir display is **above** everything else. This is true for the surface player and also our [RichWebview](https://github.com/myflashlab/webView-ANE) extension and also [the Native Facebook Like button](https://github.com/myflashlab/facebook-ANE).
* no matter what your AdobeAir content is, Starling or not, all of our Native extensions can sit over it with no problem.
* They won't be added to Starling display list or flash display list so you can not **addChild** them but you can control their position according to the stage.

Have you ever happened to work with Adobe's StageText? well, this kind of functionality is basically the same as what Adobe has done on their StageText.

> is it possible to have a Surface video within a moveable Starling DisplayObject?

you can't but considering that you have have x,y control over it, you can pretend to the end user that it is inside your content. whatch this video and you will see it in action: https://www.youtube.com/watch?v=HefrQwCSkKE

And by the way, you can run the demo version right now in your project and check everything for yourself in practice. feel free to do that.
