### ISSUE TITLE
Videos only playing if they are stored on SD card?

### ISSUE THREAD

**Issue by RoxyG** [myflashlab/surfaceVideoPlayer-ANE#4]
Hi,

I'm trying to use the ane to play a video located on device. The video is downloaded as part of the content of our app and is stored in  applicationStorgeDirectory (this is on the device storage and we want it to be like this)

The video is not playing when I use the ane, meaning I attach  the video, i get the message the Video file is available, I call play method to play it but I get only a black screen (no error event raised). Tried this on android only.

The actual video is ok - i can play it android native and I can play it using StageVideo of AIR

Just noticed that the ane is playing videos only on SD card. Is this true?
Some devices do not have an SD card, not sure I understood well if the video is playing only on SD card.

Thank you for your help.
Roxana Grunwald

**Comment by myflashlab** [comment]
by sd card, we don't mean the actual mountable card. The extension requires your file to be in File.documentsDirectory.

you're able to run the demo project here in Github, right?

**Comment by RoxyG** [comment]
Ok, I understand, however is it not possible to play the the video files if they are stored in applicationStorageDirectory? I see that a solution is to copy the file to documentsDirectory, I would like to avoid doing this.

Our content is around 400 MB of video files. The reason we are storing in applicationStorageDirectory is that if we store them in another location the user will be able to access and delete the files. 

I can copy the video file to documentsDirectory, play it and after that delete it, however I rather not do this if there are other options.

I’ve tried to run the Demo app, did not succeed yet, I see white screen with only the text : Surface video player V2.9 for Adobe Air. Don’t see the buttons nor the video player.

**Comment by myflashlab** [comment]
Please upgrade to the latest version and now you can play videos from ```File.applicationStorageDirectory``` too.
