### ISSUE TITLE
ArgumentError: Error #3500

### ISSUE THREAD

**Issue by wigginsray** [myflashlab/surfaceVideoPlayer-ANE#5]
Not sure what I'm doing wrong - but I get the error below with the code here. Developing for IOS using AIR 20. Using the ANE.

```
package  {
	
	import flash.display.MovieClip;
	 import com.myflashlab.air.extensions.player.surface.SurfacePlayer;
     import com.myflashlab.air.extensions.player.surface.SurfacePlayerEvent;
     import com.myflashlab.air.extensions.player.surface.SurfaceVideoLocation;
	import flash.filesystem.File;
	import flash.events.Event;
	import flash.display.Stage;
	
	
	public class mainVideoTest extends MovieClip {
		
		var _ex:SurfacePlayer;

		public function mainVideoTest() {
			if (stage) init(); 
 			else addEventListener(Event.ADDED_TO_STAGE, init); 
		}

		
		private function init(e:Event=null):void{
			SurfacePlayer.clubId = "ray@*******.com";
			_ex = new SurfacePlayer(this.stage);
			_ex.init(1, 1, 1024, 768, true); 
			
		}
		private function onTargetVideoAvailability(e:Event){
			_ex.play();
		}
		
	}
	
}
```

[SWF] videotest2.swf - 921 bytes after decompression
ArgumentError: Error #3500: The extension context does not have a method with the name command.
	at flash.external::ExtensionContext/_call()
	at flash.external::ExtensionContext/call()
	at com.myflashlab.air.extensions.player.surface::Android/init()
	at com.myflashlab.air.extensions.player.surface::SurfacePlayer/init()
	at mainVideoTest/init()[W:\AIR ANEs\mainVideoTest.as:25]
	at mainVideoTest()[W:\AIR ANEs\mainVideoTest.as:17]
	at runtime::ContentPlayer/loadInitialContent()
	at runtime::ContentPlayer/playRawContent()
	at runtime::ContentPlayer/playContent()
	at runtime::AppRunner/run()
	at ADLAppEntry/run()
	at global/runtime::ADLEntry()
[UnloadSWF] videotest2.swf
Test Movie terminated.

**Comment by myflashlab** [comment]
1) do not test on a simulator. you will need a real device to test on.
2) recheck your manifest .xml file and see if you are actually embedding the ANE in your package?

**Comment by myflashlab** [comment]
You may also find these videos helpful https://www.youtube.com/playlist?list=PL_mmSjScdnxnSDTMYb1iDX4LemhIJrt1O
