### ISSUE TITLE
Locating files on Android

### ISSUE THREAD

**Issue by crooksy88** [myflashlab/surfaceVideoPlayer-ANE#6]
Hi, I'm using your Surface Video ANE on both iOS and Android with some success.
On Android however I am having to copy the files to the applicationStorageDirectory as in the Demo code with 

if (!dis.exists) src.copyTo(dis);

This is somewhat of a problem for me as I include lots of small video files within the app bundle.

I'm not sure if this is of any use or interest to you but whilst testing a different video playing ANE I was able to access and play a video file which was contained in the application bundle on both iOS and Android without first copying the file. This might suggest that the video isn't being compressed on Android as you currently seem to think.

I'm using AIR 20.0.0.196
iOS 9.1
Android 4.3

The following AS3 creates a string URL path that is passed to the ANE. The only difference being iOS requires an additional file separator.

In this example I am storing all my video files within a folder named 'includes'.

var path:String;
if (OSType == "Android") {
path = File.applicationDirectory.nativePath + "includes" + File.separator +"MyVideo.mp4";
} else {  
path = File.applicationDirectory.nativePath + File.separator + "includes" + File.separator +"MyVideo.mp4";  
}

Perhaps investigating this might help you create a SurfaceVideo ANE which doesn't need to make a copy of the files first.

**Comment by myflashlab** [comment]
maybe adobe has fixed the compression problem in their latest SDK because on Android, video or sound files are not supposed to be compressed at all. Thanks for bringing this to our attention. we will investigate on this and will update this ticket as soon as we can.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
