### ISSUE TITLE
Black flash when video is loaded

### ISSUE THREAD

**Issue by crooksy88** [myflashlab/surfaceVideoPlayer-ANE#7]
As the title suggests, when I load and play a mp4 video file using the Surface Video ANE I get black flash just before the video appears.

Has anyone come across this before and can anything be done to remove this?

Thanks,

Mark

**Comment by myflashlab** [comment]
you mean the video won't play at all?

**Comment by crooksy88** [comment]
No, the video does play. But as it loads I get a flash of white, then a flash of black, then the video appears. I have a white 'torn paper' graphic here so you don't see the white flash but it is there.

[SurfaceVideo.mp4.zip](https://github.com/myflashlab/surfaceVideoPlayer-ANE/files/94716/SurfaceVideo.mp4.zip)

**Comment by crooksy88** [comment]
No, the video does play. But as it loads I get a flash of white, then a flash of black, then the video appears. I have a white 'torn paper' graphic here so you don't see the white flash but it is there.
[SurfaceVideo2.mp4.zip](https://github.com/myflashlab/surfaceVideoPlayer-ANE/files/94849/SurfaceVideo2.mp4.zip)

**Comment by myflashlab** [comment]
I'm not yet clear what you mean. the video you posted above does not have any black screen! so, I'm not sure what I am looking at exactly! Anyhow, when you attach a video to your project, the native player library is being initialized on your stage so maybe that's the black area you are talking about?

well, that's the default behavior; but you still can do some tricks to avoid it. place the video x/y position somewhere outside the stage then relocate it to where you need it whenever you need to.

**Comment by crooksy88** [comment]
Thanks for replying.

If you imagine the videos all start with a green background as the first frame. Hopefully you can see the first black screen as each video is loaded.

Having said that, your workaround does seem to do the trick. I setPosition off screen and attachVideo. Then when the PLAYING status is triggered I setPosition to the right values. :)

Thanks, 

Mark

**Comment by myflashlab** [comment]
good to know the trick worked :)
