### ISSUE TITLE
auto run of YouTube Videos

### ISSUE THREAD

**Issue by KangPrince** [myflashlab/surfaceVideoPlayer-ANE#9]
Hi, there.
I want auto run mode of YouTube Videos in my App.
You say “You can even play YouTube videos in your app if you are using our YouTube parser library. please notice that this surface player can play local videos only, so even if you wish to play a YouTube video, you need to download it first and then play it back. If you want to stream an online video though, like a YouTube video, you should try our fullscreen ANE player.”

For the auto run, I want to use the surface embedded video player ANE. But I don’t know how to use your YouTube parser library. Can I download YouTube videos with the YouTube parser library?

Thank you!

**Comment by myflashlab** [comment]
Yes, the job of the YouTube parser (Which is an open source project) is to parse a YouTube link and find the direct link to the videos to download. sample use case is shown in the YouTube parser project repository.
